// coped directly from GLFW mouse button codes
#pragma once

#define MAU_MOUSE_BUTTON_1 0
#define MAU_MOUSE_BUTTON_2 1
#define MAU_MOUSE_BUTTON_3 2
#define MAU_MOUSE_BUTTON_4 3
#define MAU_MOUSE_BUTTON_5 4
#define MAU_MOUSE_BUTTON_6 5
#define MAU_MOUSE_BUTTON_7 6
#define MAU_MOUSE_BUTTON_8 7
#define MAU_MOUSE_BUTTON_LAST MAU_MOUSE_BUTTON_8
#define MAU_MOUSE_BUTTON_LEFT MAU_MOUSE_BUTTON_1
#define MAU_MOUSE_BUTTON_RIGHT MAU_MOUSE_BUTTON_2
#define MAU_MOUSE_BUTTON_MIDDLE MAU_MOUSE_BUTTON_3
